version: "1"
services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true
    dockerCommand: "n8n start"
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 5
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_ACTIVE
        value: false
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: GENERIC_TIMEZONE
        value: America/Bogota
      - key: OLLAMA_HOST
        fromService:
          type: web
          name: ollama
          property: host
      - key: OLLAMA_PORT
        fromService:
          type: web
          name: ollama
          property: port
      - key: OLLAMA_URL
        value: "http://ollama:11434"

  - type: web
    name: ollama
    env: docker
    plan: starter
    disk:
      name: ollama_models
      mountPath: /root/.ollama
      sizeGB: 10
